app = "le-stelle-3x3"

[build]
  dockerfile = "Dockerfile"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[services]]
  internal_port = 8080

[mounts]
  source = "sqlite_data"
  destination = "/app/data"
